### ISSUE TITLE
There is an issue with your website.

### ISSUE THREAD

**Issue by KevinMueller06** [vergessene/Library-Needle#31]
It redirects to a video from a weird old grandma.
https://sugisaru.rip/

**Comment by KevinMueller06** [comment]
@KevinMueller06 @KitsuneAlex @vergessene @FlorianMichael @BunnyGirlLena Please review

**Comment by vergessene** [comment]
ain't my domain.
why are ppl. obsessed with me, their struggle is real :sob:
